/**
 * data.js — All static data for the fake profile generator
 * Countries, states/provinces, names, cities, streets, occupations, etc.
 */

const DATA = {
  // ──────────────────────────────────────────────────────────
  // Countries with metadata
  // ──────────────────────────────────────────────────────────
  countries: {
    US: {
      name: "United States",
      code: "+1",
      currency: "USD",
      currencySymbol: "$",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "90210",
      phoneFormat: "(###) ###-####",
      ethnicitySuggestions: ["Caucasian", "African American", "Hispanic", "Asian American", "Multiracial"],
    },
    UK: {
      name: "United Kingdom",
      code: "+44",
      currency: "GBP",
      currencySymbol: "£",
      postalFormat: "AA## #AA",
      postalRegex: /^[A-Z]{1,2}\d[A-Z\d]? ?\d[A-Z]{2}$/i,
      postalExample: "SW1A 1AA",
      phoneFormat: "##### ######",
      ethnicitySuggestions: ["British White", "British Asian", "Black British", "Mixed", "Other"],
    },
    CA: {
      name: "Canada",
      code: "+1",
      currency: "CAD",
      currencySymbol: "CA$",
      postalFormat: "A#A #A#",
      postalRegex: /^[A-Z]\d[A-Z] \d[A-Z]\d$/i,
      postalExample: "K1A 0A9",
      phoneFormat: "(###) ###-####",
      ethnicitySuggestions: ["Canadian White", "South Asian Canadian", "Chinese Canadian", "Black Canadian", "Multiracial"],
    },
    AU: {
      name: "Australia",
      code: "+61",
      currency: "AUD",
      currencySymbol: "A$",
      postalFormat: "#### (4 digits)",
      postalRegex: /^\d{4}$/,
      postalExample: "2000",
      phoneFormat: "0### ### ###",
      ethnicitySuggestions: ["Australian White", "Aboriginal", "Chinese Australian", "Indian Australian", "Multiracial"],
    },
    IN: {
      name: "India",
      code: "+91",
      currency: "INR",
      currencySymbol: "₹",
      postalFormat: "###### (6 digits)",
      postalRegex: /^\d{6}$/,
      postalExample: "400001",
      phoneFormat: "##### #####",
      ethnicitySuggestions: ["North Indian", "South Indian", "Bengali", "Gujarati", "Punjabi"],
    },
    DE: {
      name: "Germany",
      code: "+49",
      currency: "EUR",
      currencySymbol: "€",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "10115",
      phoneFormat: "#### #######",
      ethnicitySuggestions: ["German", "Turkish German", "Polish German", "Russian German", "Other European"],
    },
    FR: {
      name: "France",
      code: "+33",
      currency: "EUR",
      currencySymbol: "€",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "75001",
      phoneFormat: "## ## ## ## ##",
      ethnicitySuggestions: ["French White", "North African", "Sub-Saharan African", "Asian French", "Mixed"],
    },
    JP: {
      name: "Japan",
      code: "+81",
      currency: "JPY",
      currencySymbol: "¥",
      postalFormat: "###-#### (7 digits)",
      postalRegex: /^\d{3}-\d{4}$/,
      postalExample: "100-0001",
      phoneFormat: "0##-####-####",
      ethnicitySuggestions: ["Japanese"],
    },
    BR: {
      name: "Brazil",
      code: "+55",
      currency: "BRL",
      currencySymbol: "R$",
      postalFormat: "#####-### (8 digits)",
      postalRegex: /^\d{5}-\d{3}$/,
      postalExample: "01310-100",
      phoneFormat: "(##) #####-####",
      ethnicitySuggestions: ["White Brazilian", "Mixed Brazilian", "Black Brazilian", "Asian Brazilian", "Indigenous"],
    },
    MX: {
      name: "Mexico",
      code: "+52",
      currency: "MXN",
      currencySymbol: "MX$",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "06600",
      phoneFormat: "## #### ####",
      ethnicitySuggestions: ["Mestizo", "Indigenous Mexican", "White Mexican", "Mulato", "Asian Mexican"],
    },
    KR: {
      name: "South Korea",
      code: "+82",
      currency: "KRW",
      currencySymbol: "₩",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "03000",
      phoneFormat: "0##-####-####",
      ethnicitySuggestions: ["Korean"],
    },
    NG: {
      name: "Nigeria",
      code: "+234",
      currency: "NGN",
      currencySymbol: "₦",
      postalFormat: "###### (6 digits)",
      postalRegex: /^\d{6}$/,
      postalExample: "100001",
      phoneFormat: "0### ### ####",
      ethnicitySuggestions: ["Yoruba", "Igbo", "Hausa", "Fulani", "Ijaw"],
    },
    ZA: {
      name: "South Africa",
      code: "+27",
      currency: "ZAR",
      currencySymbol: "R",
      postalFormat: "#### (4 digits)",
      postalRegex: /^\d{4}$/,
      postalExample: "8001",
      phoneFormat: "0## ### ####",
      ethnicitySuggestions: ["Zulu", "Xhosa", "Afrikaner", "Indian South African", "Coloured"],
    },
    PK: {
      name: "Pakistan",
      code: "+92",
      currency: "PKR",
      currencySymbol: "Rs",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "44000",
      phoneFormat: "0### #######",
      ethnicitySuggestions: ["Punjabi", "Sindhi", "Pashtun", "Baloch", "Muhajir"],
    },
    IT: {
      name: "Italy",
      code: "+39",
      currency: "EUR",
      currencySymbol: "€",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "00100",
      phoneFormat: "### ### ####",
      ethnicitySuggestions: ["Italian", "Romanian Italian", "North African Italian", "Multiracial", "Other European"],
    },
    ES: {
      name: "Spain",
      code: "+34",
      currency: "EUR",
      currencySymbol: "€",
      postalFormat: "##### (5 digits)",
      postalRegex: /^\d{5}$/,
      postalExample: "28001",
      phoneFormat: "### ### ###",
      ethnicitySuggestions: ["Spanish White", "North African Spanish", "Latin American Spanish", "Romanian Spanish", "Other"],
    },
  },

  // ──────────────────────────────────────────────────────────
  // States/Provinces by country
  // ──────────────────────────────────────────────────────────
  states: {
    US: [
      { name: "Alabama", abbr: "AL", cities: ["Birmingham", "Montgomery", "Huntsville", "Mobile", "Tuscaloosa"] },
      { name: "Alaska", abbr: "AK", cities: ["Anchorage", "Fairbanks", "Juneau", "Sitka", "Ketchikan"] },
      { name: "Arizona", abbr: "AZ", cities: ["Phoenix", "Tucson", "Mesa", "Chandler", "Scottsdale"] },
      { name: "Arkansas", abbr: "AR", cities: ["Little Rock", "Fort Smith", "Fayetteville", "Springdale", "Jonesboro"] },
      { name: "California", abbr: "CA", cities: ["Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno"] },
      { name: "Colorado", abbr: "CO", cities: ["Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood"] },
      { name: "Connecticut", abbr: "CT", cities: ["Bridgeport", "New Haven", "Hartford", "Stamford", "Waterbury"] },
      { name: "Delaware", abbr: "DE", cities: ["Wilmington", "Dover", "Newark", "Middletown", "Smyrna"] },
      { name: "Florida", abbr: "FL", cities: ["Jacksonville", "Miami", "Tampa", "Orlando", "St. Petersburg"] },
      { name: "Georgia", abbr: "GA", cities: ["Atlanta", "Augusta", "Columbus", "Macon", "Savannah"] },
      { name: "Hawaii", abbr: "HI", cities: ["Honolulu", "Pearl City", "Hilo", "Kailua", "Waipahu"] },
      { name: "Idaho", abbr: "ID", cities: ["Boise", "Meridian", "Nampa", "Idaho Falls", "Pocatello"] },
      { name: "Illinois", abbr: "IL", cities: ["Chicago", "Aurora", "Rockford", "Joliet", "Naperville"] },
      { name: "Indiana", abbr: "IN", cities: ["Indianapolis", "Fort Wayne", "Evansville", "South Bend", "Carmel"] },
      { name: "Iowa", abbr: "IA", cities: ["Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Iowa City"] },
      { name: "Kansas", abbr: "KS", cities: ["Wichita", "Overland Park", "Kansas City", "Topeka", "Olathe"] },
      { name: "Kentucky", abbr: "KY", cities: ["Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington"] },
      { name: "Louisiana", abbr: "LA", cities: ["New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette"] },
      { name: "Maine", abbr: "ME", cities: ["Portland", "Lewiston", "Bangor", "South Portland", "Auburn"] },
      { name: "Maryland", abbr: "MD", cities: ["Baltimore", "Frederick", "Rockville", "Gaithersburg", "Bowie"] },
      { name: "Massachusetts", abbr: "MA", cities: ["Boston", "Worcester", "Springfield", "Cambridge", "Lowell"] },
      { name: "Michigan", abbr: "MI", cities: ["Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor"] },
      { name: "Minnesota", abbr: "MN", cities: ["Minneapolis", "Saint Paul", "Rochester", "Duluth", "Bloomington"] },
      { name: "Mississippi", abbr: "MS", cities: ["Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi"] },
      { name: "Missouri", abbr: "MO", cities: ["Kansas City", "St. Louis", "Springfield", "Columbia", "Independence"] },
      { name: "Montana", abbr: "MT", cities: ["Billings", "Missoula", "Great Falls", "Bozeman", "Butte"] },
      { name: "Nebraska", abbr: "NE", cities: ["Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney"] },
      { name: "Nevada", abbr: "NV", cities: ["Las Vegas", "Henderson", "Reno", "North Las Vegas", "Sparks"] },
      { name: "New Hampshire", abbr: "NH", cities: ["Manchester", "Nashua", "Concord", "Derry", "Dover"] },
      { name: "New Jersey", abbr: "NJ", cities: ["Newark", "Jersey City", "Paterson", "Elizabeth", "Trenton"] },
      { name: "New Mexico", abbr: "NM", cities: ["Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell"] },
      { name: "New York", abbr: "NY", cities: ["New York City", "Buffalo", "Rochester", "Yonkers", "Syracuse"] },
      { name: "North Carolina", abbr: "NC", cities: ["Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem"] },
      { name: "North Dakota", abbr: "ND", cities: ["Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo"] },
      { name: "Ohio", abbr: "OH", cities: ["Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron"] },
      { name: "Oklahoma", abbr: "OK", cities: ["Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Lawton"] },
      { name: "Oregon", abbr: "OR", cities: ["Portland", "Salem", "Eugene", "Gresham", "Hillsboro"] },
      { name: "Pennsylvania", abbr: "PA", cities: ["Philadelphia", "Pittsburgh", "Allentown", "Erie", "Reading"] },
      { name: "Rhode Island", abbr: "RI", cities: ["Providence", "Cranston", "Warwick", "Pawtucket", "East Providence"] },
      { name: "South Carolina", abbr: "SC", cities: ["Columbia", "Charleston", "North Charleston", "Mount Pleasant", "Rock Hill"] },
      { name: "South Dakota", abbr: "SD", cities: ["Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown"] },
      { name: "Tennessee", abbr: "TN", cities: ["Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville"] },
      { name: "Texas", abbr: "TX", cities: ["Houston", "San Antonio", "Dallas", "Austin", "Fort Worth"] },
      { name: "Utah", abbr: "UT", cities: ["Salt Lake City", "West Valley City", "Provo", "West Jordan", "Orem"] },
      { name: "Vermont", abbr: "VT", cities: ["Burlington", "South Burlington", "Rutland", "Essex Junction", "Montpelier"] },
      { name: "Virginia", abbr: "VA", cities: ["Virginia Beach", "Norfolk", "Chesapeake", "Richmond", "Newport News"] },
      { name: "Washington", abbr: "WA", cities: ["Seattle", "Spokane", "Tacoma", "Vancouver", "Bellevue"] },
      { name: "West Virginia", abbr: "WV", cities: ["Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling"] },
      { name: "Wisconsin", abbr: "WI", cities: ["Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine"] },
      { name: "Wyoming", abbr: "WY", cities: ["Cheyenne", "Casper", "Laramie", "Gillette", "Rock Springs"] },
    ],
    UK: [
      { name: "England", abbr: "ENG", cities: ["London", "Manchester", "Birmingham", "Leeds", "Liverpool", "Sheffield", "Bristol", "Newcastle"] },
      { name: "Scotland", abbr: "SCT", cities: ["Edinburgh", "Glasgow", "Aberdeen", "Dundee", "Inverness", "Stirling"] },
      { name: "Wales", abbr: "WLS", cities: ["Cardiff", "Swansea", "Newport", "Wrexham", "Barry"] },
      { name: "Northern Ireland", abbr: "NIR", cities: ["Belfast", "Derry", "Lisburn", "Newry", "Armagh"] },
    ],
    CA: [
      { name: "Alberta", abbr: "AB", cities: ["Calgary", "Edmonton", "Red Deer", "Lethbridge", "Fort McMurray"] },
      { name: "British Columbia", abbr: "BC", cities: ["Vancouver", "Victoria", "Kelowna", "Abbotsford", "Surrey"] },
      { name: "Manitoba", abbr: "MB", cities: ["Winnipeg", "Brandon", "Steinbach", "Thompson", "Portage la Prairie"] },
      { name: "New Brunswick", abbr: "NB", cities: ["Moncton", "Saint John", "Fredericton", "Dieppe", "Riverview"] },
      { name: "Newfoundland and Labrador", abbr: "NL", cities: ["St. John's", "Mount Pearl", "Corner Brook", "Grand Falls-Windsor"] },
      { name: "Nova Scotia", abbr: "NS", cities: ["Halifax", "Cape Breton", "Truro", "New Glasgow", "Dartmouth"] },
      { name: "Ontario", abbr: "ON", cities: ["Toronto", "Ottawa", "Mississauga", "Hamilton", "London", "Brampton"] },
      { name: "Prince Edward Island", abbr: "PE", cities: ["Charlottetown", "Summerside", "Stratford", "Cornwall"] },
      { name: "Quebec", abbr: "QC", cities: ["Montreal", "Quebec City", "Laval", "Gatineau", "Longueuil"] },
      { name: "Saskatchewan", abbr: "SK", cities: ["Saskatoon", "Regina", "Prince Albert", "Moose Jaw", "Swift Current"] },
    ],
    AU: [
      { name: "New South Wales", abbr: "NSW", cities: ["Sydney", "Newcastle", "Wollongong", "Maitland", "Canberra"] },
      { name: "Victoria", abbr: "VIC", cities: ["Melbourne", "Geelong", "Ballarat", "Bendigo", "Shepparton"] },
      { name: "Queensland", abbr: "QLD", cities: ["Brisbane", "Gold Coast", "Cairns", "Townsville", "Sunshine Coast"] },
      { name: "Western Australia", abbr: "WA", cities: ["Perth", "Mandurah", "Bunbury", "Geraldton", "Kalgoorlie"] },
      { name: "South Australia", abbr: "SA", cities: ["Adelaide", "Mount Gambier", "Whyalla", "Murray Bridge", "Port Augusta"] },
      { name: "Tasmania", abbr: "TAS", cities: ["Hobart", "Launceston", "Devonport", "Burnie", "Ulverstone"] },
      { name: "Northern Territory", abbr: "NT", cities: ["Darwin", "Alice Springs", "Palmerston", "Katherine"] },
      { name: "Australian Capital Territory", abbr: "ACT", cities: ["Canberra", "Tuggeranong", "Belconnen", "Gungahlin"] },
    ],
    IN: [
      { name: "Andhra Pradesh", abbr: "AP", cities: ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"] },
      { name: "Delhi", abbr: "DL", cities: ["New Delhi", "Delhi", "Dwarka", "Rohini", "Saket"] },
      { name: "Gujarat", abbr: "GJ", cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Gandhinagar"] },
      { name: "Karnataka", abbr: "KA", cities: ["Bengaluru", "Mysuru", "Hubli", "Mangaluru", "Belagavi"] },
      { name: "Kerala", abbr: "KL", cities: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kannur"] },
      { name: "Maharashtra", abbr: "MH", cities: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"] },
      { name: "Punjab", abbr: "PB", cities: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Chandigarh"] },
      { name: "Rajasthan", abbr: "RJ", cities: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Udaipur"] },
      { name: "Tamil Nadu", abbr: "TN", cities: ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem"] },
      { name: "Uttar Pradesh", abbr: "UP", cities: ["Lucknow", "Kanpur", "Agra", "Varanasi", "Prayagraj"] },
      { name: "West Bengal", abbr: "WB", cities: ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Bardhaman"] },
      { name: "Telangana", abbr: "TS", cities: ["Hyderabad", "Warangal", "Nizamabad", "Karimnagar", "Ramagundam"] },
    ],
    DE: [
      { name: "Bavaria", abbr: "BY", cities: ["Munich", "Nuremberg", "Augsburg", "Regensburg", "Würzburg"] },
      { name: "Berlin", abbr: "BE", cities: ["Berlin", "Mitte", "Charlottenburg", "Neukölln", "Pankow"] },
      { name: "Brandenburg", abbr: "BB", cities: ["Potsdam", "Cottbus", "Brandenburg an der Havel", "Frankfurt (Oder)"] },
      { name: "Bremen", abbr: "HB", cities: ["Bremen", "Bremerhaven"] },
      { name: "Hamburg", abbr: "HH", cities: ["Hamburg", "Altona", "Wandsbek", "Eimsbüttel"] },
      { name: "Hesse", abbr: "HE", cities: ["Frankfurt", "Wiesbaden", "Kassel", "Darmstadt", "Offenbach"] },
      { name: "Lower Saxony", abbr: "NI", cities: ["Hanover", "Braunschweig", "Osnabrück", "Oldenburg", "Wolfsburg"] },
      { name: "North Rhine-Westphalia", abbr: "NW", cities: ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisburg"] },
      { name: "Rhineland-Palatinate", abbr: "RP", cities: ["Mainz", "Ludwigshafen", "Koblenz", "Trier", "Kaiserslautern"] },
      { name: "Saxony", abbr: "SN", cities: ["Dresden", "Leipzig", "Chemnitz", "Zwickau", "Plauen"] },
    ],
    FR: [
      { name: "Île-de-France", abbr: "IDF", cities: ["Paris", "Boulogne-Billancourt", "Saint-Denis", "Argenteuil", "Versailles"] },
      { name: "Auvergne-Rhône-Alpes", abbr: "ARA", cities: ["Lyon", "Grenoble", "Saint-Étienne", "Clermont-Ferrand", "Annecy"] },
      { name: "Nouvelle-Aquitaine", abbr: "NAQ", cities: ["Bordeaux", "Limoges", "Pau", "Bayonne", "Niort"] },
      { name: "Occitanie", abbr: "OCC", cities: ["Toulouse", "Montpellier", "Nîmes", "Perpignan", "Béziers"] },
      { name: "Hauts-de-France", abbr: "HDF", cities: ["Lille", "Amiens", "Roubaix", "Tourcoing", "Dunkirk"] },
      { name: "Grand Est", abbr: "GES", cities: ["Strasbourg", "Reims", "Metz", "Nancy", "Mulhouse"] },
      { name: "Normandy", abbr: "NOR", cities: ["Rouen", "Caen", "Le Havre", "Cherbourg", "Évreux"] },
      { name: "Provence-Alpes-Côte d'Azur", abbr: "PAC", cities: ["Marseille", "Nice", "Toulon", "Aix-en-Provence", "Avignon"] },
      { name: "Pays de la Loire", abbr: "PDL", cities: ["Nantes", "Angers", "Le Mans", "Saint-Nazaire", "Laval"] },
      { name: "Bretagne", abbr: "BRE", cities: ["Rennes", "Brest", "Quimper", "Lorient", "Vannes"] },
    ],
    JP: [
      { name: "Tokyo", abbr: "TK", cities: ["Shinjuku", "Shibuya", "Minato", "Bunkyo", "Setagaya"] },
      { name: "Osaka", abbr: "OS", cities: ["Osaka", "Sakai", "Higashiosaka", "Hirakata", "Toyonaka"] },
      { name: "Kanagawa", abbr: "KN", cities: ["Yokohama", "Kawasaki", "Sagamihara", "Fujisawa", "Yokosuka"] },
      { name: "Aichi", abbr: "AI", cities: ["Nagoya", "Toyota", "Okazaki", "Ichinomiya", "Kasugai"] },
      { name: "Saitama", abbr: "ST", cities: ["Saitama", "Kawaguchi", "Tokorozawa", "Kasukabe", "Ageo"] },
      { name: "Hokkaido", abbr: "HK", cities: ["Sapporo", "Asahikawa", "Hakodate", "Kushiro", "Obihiro"] },
      { name: "Kyoto", abbr: "KY", cities: ["Kyoto", "Uji", "Kameoka", "Joyo", "Maizuru"] },
      { name: "Fukuoka", abbr: "FK", cities: ["Fukuoka", "Kitakyushu", "Kurume", "Omuta", "Iizuka"] },
    ],
    BR: [
      { name: "São Paulo", abbr: "SP", cities: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo", "Santo André"] },
      { name: "Rio de Janeiro", abbr: "RJ", cities: ["Rio de Janeiro", "São Gonçalo", "Duque de Caxias", "Nova Iguaçu", "Niterói"] },
      { name: "Minas Gerais", abbr: "MG", cities: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora", "Betim"] },
      { name: "Bahia", abbr: "BA", cities: ["Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari", "Itabuna"] },
      { name: "Paraná", abbr: "PR", cities: ["Curitiba", "Londrina", "Maringá", "Ponta Grossa", "Cascavel"] },
      { name: "Rio Grande do Sul", abbr: "RS", cities: ["Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas", "Santa Maria"] },
      { name: "Pernambuco", abbr: "PE", cities: ["Recife", "Caruaru", "Petrolina", "Olinda", "Paulista"] },
      { name: "Ceará", abbr: "CE", cities: ["Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú", "Sobral"] },
    ],
    MX: [
      { name: "Mexico City", abbr: "CDMX", cities: ["Mexico City", "Iztapalapa", "Gustavo A. Madero", "Álvaro Obregón", "Tlalpan"] },
      { name: "Jalisco", abbr: "JAL", cities: ["Guadalajara", "Zapopan", "Tlaquepaque", "Tonalá", "Puerto Vallarta"] },
      { name: "Nuevo León", abbr: "NL", cities: ["Monterrey", "Guadalupe", "San Nicolás de los Garza", "Apodaca", "General Escobedo"] },
      { name: "Puebla", abbr: "PUE", cities: ["Puebla", "Tehuacán", "San Andrés Cholula", "Atlixco", "Huauchinango"] },
      { name: "Guanajuato", abbr: "GTO", cities: ["León", "Irapuato", "Celaya", "Salamanca", "Guanajuato"] },
      { name: "Veracruz", abbr: "VER", cities: ["Veracruz", "Xalapa", "Coatzacoalcos", "Córdoba", "Orizaba"] },
      { name: "Chihuahua", abbr: "CHH", cities: ["Chihuahua", "Ciudad Juárez", "Delicias", "Cuauhtémoc", "Hidalgo del Parral"] },
      { name: "Baja California", abbr: "BCN", cities: ["Tijuana", "Mexicali", "Ensenada", "Tecate", "Rosarito"] },
    ],
    KR: [
      { name: "Seoul", abbr: "SEL", cities: ["Gangnam", "Mapo", "Yongsan", "Jongno", "Seongdong"] },
      { name: "Busan", abbr: "BUS", cities: ["Haeundae", "Nam-gu", "Yeonje", "Suyeong", "Saha"] },
      { name: "Incheon", abbr: "ICN", cities: ["Bupyeong", "Namdong", "Seo-gu", "Michuhol", "Gyeyang"] },
      { name: "Gyeonggi", abbr: "GG", cities: ["Suwon", "Seongnam", "Bucheon", "Goyang", "Yongin"] },
      { name: "Gyeongsang", abbr: "GS", cities: ["Daegu", "Changwon", "Pohang", "Gimhae", "Jinju"] },
      { name: "Chungcheong", abbr: "CC", cities: ["Daejeon", "Cheongju", "Cheonan", "Asan", "Sejong"] },
      { name: "Jeolla", abbr: "JL", cities: ["Gwangju", "Jeonju", "Suncheon", "Iksan", "Naju"] },
      { name: "Jeju", abbr: "JEJ", cities: ["Jeju City", "Seogwipo", "Aewol", "Jocheon"] },
    ],
    NG: [
      { name: "Lagos", abbr: "LA", cities: ["Lagos", "Ikeja", "Agege", "Alimosho", "Eti-Osa"] },
      { name: "Kano", abbr: "KN", cities: ["Kano", "Dala", "Gwale", "Fagge", "Nassarawa"] },
      { name: "Rivers", abbr: "RI", cities: ["Port Harcourt", "Obio-Akpor", "Okrika", "Eleme", "Bonny"] },
      { name: "Oyo", abbr: "OY", cities: ["Ibadan", "Ogbomoso", "Oyo", "Iseyin", "Saki"] },
      { name: "Abuja", abbr: "FC", cities: ["Abuja", "Gwagwalada", "Kuje", "Abaji", "Kwali"] },
      { name: "Delta", abbr: "DE", cities: ["Warri", "Asaba", "Sapele", "Ughelli", "Agbor"] },
      { name: "Ogun", abbr: "OG", cities: ["Abeokuta", "Sagamu", "Ifo", "Ota", "Ilaro"] },
      { name: "Enugu", abbr: "EN", cities: ["Enugu", "Nsukka", "Agbani", "Oji River", "Udi"] },
    ],
    ZA: [
      { name: "Gauteng", abbr: "GP", cities: ["Johannesburg", "Pretoria", "Ekurhuleni", "Tshwane", "Soweto"] },
      { name: "Western Cape", abbr: "WC", cities: ["Cape Town", "Stellenbosch", "George", "Paarl", "Worcester"] },
      { name: "KwaZulu-Natal", abbr: "KZN", cities: ["Durban", "Pietermaritzburg", "Newcastle", "Richards Bay", "Empangeni"] },
      { name: "Eastern Cape", abbr: "EC", cities: ["East London", "Port Elizabeth", "Bhisho", "King William's Town", "Queenstown"] },
      { name: "Limpopo", abbr: "LP", cities: ["Polokwane", "Tzaneen", "Phalaborwa", "Mokopane", "Bela-Bela"] },
      { name: "Mpumalanga", abbr: "MP", cities: ["Nelspruit", "Witbank", "Middelburg", "Standerton", "Secunda"] },
      { name: "North West", abbr: "NW", cities: ["Rustenburg", "Klerksdorp", "Potchefstroom", "Mahikeng", "Brits"] },
      { name: "Free State", abbr: "FS", cities: ["Bloemfontein", "Welkom", "Phuthaditjhaba", "Sasolburg", "Bethlehem"] },
    ],
    PK: [
      { name: "Punjab", abbr: "PB", cities: ["Lahore", "Faisalabad", "Rawalpindi", "Gujranwala", "Multan"] },
      { name: "Sindh", abbr: "SD", cities: ["Karachi", "Hyderabad", "Sukkur", "Larkana", "Nawabshah"] },
      { name: "Khyber Pakhtunkhwa", abbr: "KP", cities: ["Peshawar", "Abbottabad", "Mardan", "Swat", "Kohat"] },
      { name: "Balochistan", abbr: "BL", cities: ["Quetta", "Turbat", "Gwadar", "Hub", "Khuzdar"] },
      { name: "Islamabad Capital Territory", abbr: "ICT", cities: ["Islamabad", "Rawat", "Kahuta", "Taxila"] },
      { name: "Azad Kashmir", abbr: "AK", cities: ["Muzaffarabad", "Mirpur", "Rawalakot", "Bhimber", "Kotli"] },
    ],
    IT: [
      { name: "Lazio", abbr: "LAZ", cities: ["Rome", "Latina", "Frosinone", "Viterbo", "Rieti"] },
      { name: "Lombardy", abbr: "LOM", cities: ["Milan", "Brescia", "Bergamo", "Monza", "Como"] },
      { name: "Veneto", abbr: "VEN", cities: ["Venice", "Verona", "Padua", "Vicenza", "Treviso"] },
      { name: "Campania", abbr: "CAM", cities: ["Naples", "Salerno", "Caserta", "Benevento", "Avellino"] },
      { name: "Sicily", abbr: "SIC", cities: ["Palermo", "Catania", "Messina", "Agrigento", "Trapani"] },
      { name: "Tuscany", abbr: "TOS", cities: ["Florence", "Prato", "Livorno", "Arezzo", "Pisa"] },
      { name: "Piedmont", abbr: "PIE", cities: ["Turin", "Novara", "Alessandria", "Asti", "Cuneo"] },
      { name: "Emilia-Romagna", abbr: "EMR", cities: ["Bologna", "Modena", "Parma", "Reggio Emilia", "Ferrara"] },
    ],
    ES: [
      { name: "Madrid", abbr: "MD", cities: ["Madrid", "Móstoles", "Alcalá de Henares", "Fuenlabrada", "Leganés"] },
      { name: "Catalonia", abbr: "CT", cities: ["Barcelona", "L'Hospitalet de Llobregat", "Badalona", "Terrassa", "Sabadell"] },
      { name: "Andalusia", abbr: "AN", cities: ["Seville", "Málaga", "Córdoba", "Granada", "Almería"] },
      { name: "Valencia", abbr: "VC", cities: ["Valencia", "Alicante", "Elche", "Castellón de la Plana", "Torrent"] },
      { name: "Basque Country", abbr: "PV", cities: ["Bilbao", "Vitoria-Gasteiz", "San Sebastián", "Barakaldo", "Getxo"] },
      { name: "Galicia", abbr: "GA", cities: ["Vigo", "A Coruña", "Ourense", "Pontevedra", "Lugo"] },
      { name: "Castile and León", abbr: "CL", cities: ["Valladolid", "Burgos", "Salamanca", "León", "Segovia"] },
      { name: "Aragon", abbr: "AR", cities: ["Zaragoza", "Huesca", "Teruel", "Calatayud", "Alcañiz"] },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // First names by gender and origin group
  // ──────────────────────────────────────────────────────────
  firstNames: {
    male: {
      western: ["James", "John", "Robert", "Michael", "William", "David", "Richard", "Joseph", "Thomas", "Christopher",
                "Charles", "Daniel", "Matthew", "Anthony", "Mark", "Donald", "Steven", "Paul", "Andrew", "Joshua",
                "Kenneth", "Kevin", "Brian", "George", "Timothy", "Ronald", "Edward", "Jason", "Jeffrey", "Ryan",
                "Jacob", "Gary", "Nicholas", "Eric", "Jonathan", "Stephen", "Larry", "Justin", "Scott", "Brandon",
                "Frank", "Benjamin", "Gregory", "Samuel", "Raymond", "Patrick", "Alexander", "Jack", "Dennis", "Jerry"],
      latin: ["Carlos", "Miguel", "José", "Luis", "Juan", "Pedro", "Fernando", "Diego", "Eduardo", "Alejandro",
              "Antonio", "Francisco", "Manuel", "Andrés", "Roberto", "Ricardo", "Rafael", "Alberto", "Sergio", "Felipe",
              "Gustavo", "Arturo", "Héctor", "Mario", "Víctor", "Salvador", "Raúl", "Óscar", "Javier", "Jorge"],
      south_asian: ["Rahul", "Arjun", "Ravi", "Suresh", "Vijay", "Arun", "Amit", "Pradeep", "Sanjay", "Rajesh",
                    "Mohammed", "Imran", "Bilal", "Usman", "Hassan", "Ahmad", "Ali", "Hamza", "Faisal", "Omar",
                    "Rohit", "Kiran", "Deepak", "Vikram", "Ashok", "Ankit", "Gaurav", "Nikhil", "Sachin", "Vikas"],
      east_asian: ["Wei", "Jian", "Ming", "Lei", "Hao", "Jun", "Zhi", "Yang", "Feng", "Long",
                   "Kenji", "Hiroshi", "Takashi", "Yuki", "Ryota", "Daisuke", "Masato", "Taro", "Kazuki", "Shota",
                   "Ji-ho", "Min-jun", "Seo-jun", "Jae-won", "Hyun-woo", "Dong-hyun", "Seong-min", "Joon", "Tae", "Woo"],
      african: ["Chukwuemeka", "Oluwaseun", "Babatunde", "Emeka", "Chidi", "Kwame", "Kofi", "Ade", "Bayo", "Tunde",
                "Sipho", "Thabo", "Lungelo", "Bongani", "Sandile", "Nkosinathi", "Phiwayinkosi", "Mthokozisi", "Siyanda", "Lethiwe"],
      german: ["Hans", "Klaus", "Werner", "Dieter", "Franz", "Friedrich", "Heinz", "Karl", "Otto", "Wolfgang",
               "Lukas", "Felix", "Jonas", "Maximilian", "Leon", "Tim", "Tobias", "Florian", "Niklas", "Jan"],
      french: ["Jean", "Pierre", "Michel", "Philippe", "François", "André", "Jacques", "René", "Louis", "Paul",
               "Hugo", "Lucas", "Léo", "Mathieu", "Baptiste", "Théo", "Antoine", "Clément", "Romain", "Nicolas"],
    },
    female: {
      western: ["Mary", "Patricia", "Jennifer", "Linda", "Barbara", "Elizabeth", "Susan", "Jessica", "Sarah", "Karen",
                "Lisa", "Nancy", "Betty", "Sandra", "Margaret", "Ashley", "Dorothy", "Kimberly", "Emily", "Donna",
                "Michelle", "Carol", "Amanda", "Melissa", "Deborah", "Stephanie", "Rebecca", "Sharon", "Laura", "Cynthia",
                "Amy", "Angela", "Helen", "Anna", "Brenda", "Pamela", "Emma", "Nicole", "Katherine", "Samantha",
                "Christine", "Debra", "Rachel", "Virginia", "Janet", "Catherine", "Maria", "Heather", "Diane", "Ruth"],
      latin: ["María", "Ana", "Carmen", "Sofía", "Valentina", "Isabella", "Camila", "Lucía", "Gabriela", "Fernanda",
              "Daniela", "Verónica", "Claudia", "Natalia", "Alejandra", "Adriana", "Paola", "Valeria", "Diana", "Laura",
              "Rosa", "Elena", "Silvia", "Teresa", "Beatriz", "Gloria", "Patricia", "Mónica", "Sandra", "Angela"],
      south_asian: ["Priya", "Anjali", "Sunita", "Pooja", "Rekha", "Anita", "Deepa", "Kavya", "Meera", "Shreya",
                    "Fatima", "Ayesha", "Zainab", "Sana", "Hina", "Nadia", "Sara", "Maria", "Amina", "Rabia",
                    "Divya", "Neha", "Swati", "Ritu", "Nisha", "Pallavi", "Aarti", "Bharti", "Sneha", "Tanya"],
      east_asian: ["Xiao", "Ying", "Li", "Fang", "Mei", "Juan", "Lin", "Hua", "Yan", "Hong",
                   "Yuki", "Sakura", "Aoi", "Hana", "Mio", "Rin", "Nana", "Yui", "Saki", "Mizuki",
                   "Ji-yeon", "So-yeon", "Min-ji", "Soo-jin", "Hye-jin", "Eun-ji", "Ji-eun", "Yeon", "Ah-ri", "Na"],
      african: ["Ngozi", "Amara", "Chisom", "Adaeze", "Kemi", "Bimpe", "Yetunde", "Sola", "Funke", "Titi",
                "Nomvula", "Zanele", "Nokuthula", "Bongiwe", "Thandi", "Phindile", "Ntombifuthi", "Zodwa", "Ayanda", "Nomalanga"],
      german: ["Ingrid", "Helga", "Ursula", "Gisela", "Elfriede", "Hildegard", "Christa", "Brigitte", "Monika", "Renate",
               "Lena", "Anna", "Sophie", "Marie", "Laura", "Julia", "Sarah", "Lisa", "Hannah", "Lea"],
      french: ["Marie", "Jeanne", "Françoise", "Catherine", "Nathalie", "Christine", "Isabelle", "Anne", "Monique", "Sophie",
               "Léa", "Camille", "Chloé", "Lucie", "Manon", "Emma", "Zoé", "Alice", "Pauline", "Charlotte"],
    },
  },

  // ──────────────────────────────────────────────────────────
  // Last names by origin group
  // ──────────────────────────────────────────────────────────
  lastNames: {
    western: ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia", "Miller", "Davis", "Wilson", "Anderson",
              "Taylor", "Thomas", "Hernandez", "Moore", "Martin", "Jackson", "Thompson", "White", "Lopez", "Lee",
              "Gonzalez", "Harris", "Clark", "Lewis", "Robinson", "Walker", "Perez", "Hall", "Young", "Allen",
              "Sanchez", "Wright", "King", "Scott", "Green", "Baker", "Adams", "Nelson", "Hill", "Ramirez",
              "Campbell", "Mitchell", "Roberts", "Carter", "Phillips", "Evans", "Turner", "Torres", "Parker", "Collins"],
    latin: ["García", "Rodríguez", "Martínez", "Hernández", "López", "González", "Pérez", "Sánchez", "Ramírez", "Cruz",
            "Torres", "Flores", "Rivera", "Gómez", "Díaz", "Reyes", "Morales", "Jiménez", "Ortiz", "Gutiérrez",
            "Chávez", "Ramos", "Moreno", "Mendoza", "Ruiz", "Álvarez", "Medina", "Aguilar", "Vargas", "Castillo"],
    south_asian: ["Sharma", "Verma", "Singh", "Kumar", "Gupta", "Patel", "Shah", "Mehta", "Joshi", "Mishra",
                  "Khan", "Ahmed", "Ali", "Malik", "Chaudhary", "Rana", "Sheikh", "Butt", "Mirza", "Qureshi",
                  "Reddy", "Nair", "Pillai", "Menon", "Iyer", "Rao", "Krishnan", "Rajan", "Bose", "Das"],
    east_asian: ["Wang", "Li", "Zhang", "Liu", "Chen", "Yang", "Huang", "Zhao", "Wu", "Zhou",
                 "Tanaka", "Sato", "Suzuki", "Watanabe", "Yamamoto", "Nakamura", "Kobayashi", "Ito", "Kato", "Yoshida",
                 "Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim"],
    african: ["Okafor", "Adeyemi", "Nwosu", "Okonkwo", "Chukwu", "Obi", "Eze", "Nnamdi", "Odunsi", "Bankole",
              "Dlamini", "Nkosi", "Khumalo", "Ndlovu", "Mthembu", "Zulu", "Mkhize", "Nxumalo", "Mahlangu", "Ngcobo"],
    german: ["Müller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann",
             "Schäfer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schröder", "Neumann", "Schwarz", "Zimmermann"],
    french: ["Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau",
             "Simon", "Laurent", "Lefebvre", "Michel", "Garcia", "David", "Bertrand", "Roux", "Vincent", "Fournier"],
  },

  // ──────────────────────────────────────────────────────────
  // Name mapping by country
  // ──────────────────────────────────────────────────────────
  countryNameGroup: {
    US: "western", UK: "western", CA: "western", AU: "western",
    IN: "south_asian", PK: "south_asian",
    DE: "german", FR: "french",
    JP: "east_asian", KR: "east_asian",
    BR: "latin", MX: "latin", ES: "latin", IT: "western",
    NG: "african", ZA: "african",
  },

  // ──────────────────────────────────────────────────────────
  // Street name components by country
  // ──────────────────────────────────────────────────────────
  streetNames: {
    US: {
      names: ["Oak", "Maple", "Cedar", "Pine", "Elm", "Washington", "Park", "Main", "Sunset", "Highland",
              "Lake", "Hill", "River", "Forest", "Meadow", "Spring", "Willow", "Canyon", "Ridge", "Valley"],
      suffixes: ["St", "Ave", "Blvd", "Dr", "Ln", "Rd", "Ct", "Way", "Pl", "Ter"],
    },
    UK: {
      names: ["High", "Church", "Station", "Park", "Manor", "Victoria", "Albert", "King", "Queen", "Green",
              "Mill", "Castle", "Bridge", "Market", "School", "Garden", "Lodge", "Heath", "Common", "Wood"],
      suffixes: ["Street", "Road", "Lane", "Avenue", "Close", "Drive", "Place", "Way", "Court", "Crescent"],
    },
    CA: {
      names: ["Maple", "Oak", "Pine", "Birch", "Elm", "Cedar", "Spruce", "Willow", "Aspen", "Heritage",
              "Royal", "Victoria", "Lakeview", "Forest", "Ridgewood", "Thornwood", "Clearview", "Brookside", "Fairview", "Hillcrest"],
      suffixes: ["St", "Ave", "Blvd", "Dr", "Ln", "Rd", "Cres", "Way", "Pl", "Ct"],
    },
    AU: {
      names: ["Eucalyptus", "Banksia", "Wattle", "Acacia", "Grevillea", "Waratah", "Bottlebrush", "Jacaranda", "Fern", "Heath",
              "George", "Elizabeth", "Victoria", "William", "James", "Charlotte", "Albert", "Collins", "King", "Queen"],
      suffixes: ["Street", "Road", "Avenue", "Drive", "Court", "Place", "Way", "Close", "Lane", "Parade"],
    },
    IN: {
      names: ["Gandhi", "Nehru", "Patel", "Ambedkar", "Tagore", "Subhash", "Rajendra", "Indira", "Lakshmi", "Sarojini",
              "MG Road", "Ring Road", "Civil Lines", "Model Town", "Sector", "New Colony", "Old Colony", "Garden", "Park", "Link"],
      suffixes: ["Road", "Street", "Nagar", "Colony", "Layout", "Extension", "Phase", "Lane", "Marg", "Path"],
    },
    DE: {
      names: ["Haupt", "Bahnhof", "Garten", "Park", "Schul", "Kirch", "Markt", "Neu", "Alt", "Berg",
              "Birken", "Buchen", "Eichen", "Linden", "Fichten", "Tannen", "Ahorn", "Rosen", "Tulpen", "Goethe"],
      suffixes: ["straße", "gasse", "weg", "platz", "ring", "allee", "damm", "pfad", "ufer", "steig"],
    },
    FR: {
      names: ["Victor Hugo", "Jean Jaurès", "Charles de Gaulle", "Aristide Briand", "Gambetta", "République", "Liberté", "Marché",
              "Eglise", "Fontaine", "Moulin", "Château", "Parc", "Prairie", "Forêt", "Vignes", "Fleurs", "Roses", "Champs", "Grande"],
      suffixes: ["Rue", "Avenue", "Boulevard", "Allée", "Chemin", "Passage", "Impasse", "Place", "Route", "Voie"],
    },
    JP: {
      names: ["Sakura", "Yuki", "Hana", "Midori", "Kawa", "Yama", "Umi", "Mori", "Tori", "Hoshi",
              "Shin", "Higashi", "Nishi", "Kita", "Minami", "Hon", "Chuo", "Soto", "Uchi", "Dai"],
      suffixes: ["-cho", "-dori", "-machi", "-ku", "-shi", "-chome", "-ban", "-go", "-district", "-ward"],
    },
    BR: {
      names: ["São Paulo", "Rio", "Pedro I", "Pedro II", "Getúlio Vargas", "das Flores", "das Palmeiras", "das Acácias",
              "do Comércio", "da Paz", "da Liberdade", "Municipal", "Central", "Principal", "Nova", "Velha", "Grande", "Pequena", "Longa", "Curta"],
      suffixes: ["Rua", "Avenida", "Travessa", "Alameda", "Praça", "Viela", "Estrada", "Rodovia", "Via", "Largo"],
    },
    MX: {
      names: ["Juárez", "Hidalgo", "Morelos", "Guerrero", "Reforma", "Independencia", "Revolución", "Constitución",
              "Cinco de Mayo", "Dieciséis de Septiembre", "Aztecas", "Olmecas", "Maya", "Tolteca", "Azteca", "Inca", "Zapoteca", "Mixteca", "Totonaca", "Huasteca"],
      suffixes: ["Calle", "Avenida", "Calzada", "Bulevar", "Carretera", "Camino", "Vía", "Circuito", "Paseo", "Privada"],
    },
    KR: {
      names: ["Gangnam", "Hongdae", "Sinchon", "Seocho", "Jamsil", "Itaewon", "Myeongdong", "Insadong", "Bukchon", "Cheongdam",
              "Dong", "Seo", "Nam", "Buk", "Jung", "Gu", "Gil", "Ro", "Daero", "Sunhwan"],
      suffixes: ["-gil", "-ro", "-daero", "-dong", "-gu", "-ri", "-myeon", "-si", "-cheon", "-sangseo"],
    },
    NG: {
      names: ["Awolowo", "Azikiwe", "Balewa", "Ekwueme", "Gowon", "Murtala", "Obasanjo", "Shagari", "Babangida", "Abubakar",
              "New", "Old", "Upper", "Lower", "North", "South", "East", "West", "Central", "Main"],
      suffixes: ["Road", "Street", "Avenue", "Close", "Drive", "Way", "Crescent", "Lane", "Boulevard", "Place"],
    },
    ZA: {
      names: ["Mandela", "Biko", "Sobukwe", "Sisulu", "Tambo", "Nkosi", "Dlamini", "Zulu", "Botha", "De Klerk",
              "Main", "Church", "Market", "Station", "Park", "Victoria", "King", "Queen", "Republic", "Freedom"],
      suffixes: ["Street", "Road", "Avenue", "Drive", "Close", "Place", "Way", "Court", "Lane", "Crescent"],
    },
    PK: {
      names: ["Iqbal", "Jinnah", "Bhutto", "Liaquat Ali", "Ayub", "Yahya", "Zia", "Benazir", "Nawaz", "Khan",
              "Garden", "Model Town", "Gulberg", "Defense", "Cantt", "Satellite Town", "Colony", "Block", "Sector", "Phase"],
      suffixes: ["Road", "Street", "Avenue", "Lane", "Gulshan", "Chowk", "Mohalla", "Bazaar", "Market", "Block"],
    },
    IT: {
      names: ["Via Roma", "Via Nazionale", "Via del Corso", "Via Cavour", "Via Manzoni", "Via Garibaldi",
              "Via Dante", "Via Verdi", "Corso Italia", "Corso Vittorio Emanuele", "Piazza", "Viale", "Lungomare", "Salita", "Discesa", "Traversa", "Vicoletto", "Rione", "Quartiere", "Borgo"],
      suffixes: ["Via", "Corso", "Piazza", "Viale", "Vicolo", "Largo", "Salita", "Traversa", "Strada", "Contrada"],
    },
    ES: {
      names: ["Gran Vía", "Paseo de Gracia", "Rambla", "Calle Mayor", "Calle Real", "Calle Nueva", "Avenida Principal",
              "Paseo Marítimo", "Calle del Mar", "Calle del Sol", "Luna", "Estrella", "Cruz", "Rey", "Reina", "Príncipe", "Infanta", "Duque", "Conde", "Marqués"],
      suffixes: ["Calle", "Avenida", "Paseo", "Rambla", "Carrer", "Carretera", "Camino", "Vía", "Plaza", "Travesía"],
    },
  },

  // ──────────────────────────────────────────────────────────
  // Occupations by industry
  // ──────────────────────────────────────────────────────────
  occupations: {
    tech: [
      { title: "Software Engineer", seniorTitle: "Senior Software Engineer" },
      { title: "Frontend Developer", seniorTitle: "Senior Frontend Developer" },
      { title: "Backend Developer", seniorTitle: "Lead Backend Developer" },
      { title: "Data Scientist", seniorTitle: "Principal Data Scientist" },
      { title: "DevOps Engineer", seniorTitle: "Senior DevOps Engineer" },
      { title: "Product Manager", seniorTitle: "Director of Product" },
      { title: "UX Designer", seniorTitle: "Lead UX Designer" },
      { title: "QA Engineer", seniorTitle: "QA Lead" },
      { title: "Systems Analyst", seniorTitle: "Senior Systems Analyst" },
      { title: "Network Administrator", seniorTitle: "Senior Network Administrator" },
    ],
    healthcare: [
      { title: "Registered Nurse", seniorTitle: "Head Nurse" },
      { title: "Medical Technician", seniorTitle: "Senior Medical Technician" },
      { title: "Pharmacist", seniorTitle: "Chief Pharmacist" },
      { title: "Physical Therapist", seniorTitle: "Senior Physical Therapist" },
      { title: "Lab Technician", seniorTitle: "Lab Supervisor" },
      { title: "Healthcare Administrator", seniorTitle: "Director of Healthcare" },
      { title: "Dental Hygienist", seniorTitle: "Lead Dental Hygienist" },
      { title: "Radiologist Technician", seniorTitle: "Senior Radiologist Technician" },
      { title: "Nutritionist", seniorTitle: "Chief Nutritionist" },
      { title: "Medical Coder", seniorTitle: "Senior Medical Coder" },
    ],
    education: [
      { title: "Teacher", seniorTitle: "Head Teacher" },
      { title: "Librarian", seniorTitle: "Chief Librarian" },
      { title: "School Counselor", seniorTitle: "Lead School Counselor" },
      { title: "Education Coordinator", seniorTitle: "Director of Education" },
      { title: "Tutor", seniorTitle: "Senior Tutor" },
      { title: "Academic Advisor", seniorTitle: "Dean of Academics" },
      { title: "Instructional Designer", seniorTitle: "Lead Instructional Designer" },
      { title: "Training Specialist", seniorTitle: "Senior Training Specialist" },
      { title: "Curriculum Developer", seniorTitle: "Head Curriculum Developer" },
      { title: "Education Researcher", seniorTitle: "Principal Education Researcher" },
    ],
    finance: [
      { title: "Financial Analyst", seniorTitle: "Senior Financial Analyst" },
      { title: "Accountant", seniorTitle: "Senior Accountant" },
      { title: "Bank Teller", seniorTitle: "Senior Bank Teller" },
      { title: "Investment Analyst", seniorTitle: "Portfolio Manager" },
      { title: "Loan Officer", seniorTitle: "Senior Loan Officer" },
      { title: "Insurance Agent", seniorTitle: "Senior Insurance Agent" },
      { title: "Tax Specialist", seniorTitle: "Tax Manager" },
      { title: "Risk Analyst", seniorTitle: "Senior Risk Analyst" },
      { title: "Budget Analyst", seniorTitle: "Senior Budget Analyst" },
      { title: "Compliance Officer", seniorTitle: "Compliance Manager" },
    ],
    retail: [
      { title: "Sales Associate", seniorTitle: "Store Manager" },
      { title: "Customer Service Representative", seniorTitle: "Customer Service Supervisor" },
      { title: "Retail Supervisor", seniorTitle: "Regional Manager" },
      { title: "Merchandiser", seniorTitle: "Senior Merchandiser" },
      { title: "Cashier", seniorTitle: "Head Cashier" },
      { title: "Stock Associate", seniorTitle: "Inventory Manager" },
      { title: "Visual Merchandiser", seniorTitle: "Senior Visual Merchandiser" },
      { title: "Sales Representative", seniorTitle: "Senior Sales Representative" },
      { title: "E-commerce Specialist", seniorTitle: "E-commerce Manager" },
      { title: "Buyer", seniorTitle: "Senior Buyer" },
    ],
    manufacturing: [
      { title: "Production Worker", seniorTitle: "Production Supervisor" },
      { title: "Quality Inspector", seniorTitle: "Quality Manager" },
      { title: "Machine Operator", seniorTitle: "Senior Machine Operator" },
      { title: "Maintenance Technician", seniorTitle: "Maintenance Supervisor" },
      { title: "Warehouse Associate", seniorTitle: "Warehouse Manager" },
      { title: "Forklift Operator", seniorTitle: "Senior Forklift Operator" },
      { title: "Assembly Line Worker", seniorTitle: "Assembly Supervisor" },
      { title: "Industrial Engineer", seniorTitle: "Senior Industrial Engineer" },
      { title: "Safety Officer", seniorTitle: "Safety Manager" },
      { title: "Supply Chain Coordinator", seniorTitle: "Supply Chain Manager" },
    ],
    government: [
      { title: "Administrative Officer", seniorTitle: "Senior Administrative Officer" },
      { title: "Policy Analyst", seniorTitle: "Senior Policy Analyst" },
      { title: "Public Relations Officer", seniorTitle: "PR Manager" },
      { title: "Social Worker", seniorTitle: "Senior Social Worker" },
      { title: "Tax Officer", seniorTitle: "Senior Tax Officer" },
      { title: "Postal Worker", seniorTitle: "Postal Supervisor" },
      { title: "Urban Planner", seniorTitle: "Senior Urban Planner" },
      { title: "Environmental Scientist", seniorTitle: "Senior Environmental Scientist" },
      { title: "Legal Clerk", seniorTitle: "Senior Legal Clerk" },
      { title: "Records Manager", seniorTitle: "Director of Records" },
    ],
    hospitality: [
      { title: "Hotel Receptionist", seniorTitle: "Front Desk Manager" },
      { title: "Chef", seniorTitle: "Executive Chef" },
      { title: "Restaurant Manager", seniorTitle: "Regional Restaurant Manager" },
      { title: "Event Coordinator", seniorTitle: "Senior Event Coordinator" },
      { title: "Travel Agent", seniorTitle: "Senior Travel Agent" },
      { title: "Bartender", seniorTitle: "Head Bartender" },
      { title: "Housekeeper", seniorTitle: "Housekeeping Supervisor" },
      { title: "Tour Guide", seniorTitle: "Senior Tour Guide" },
      { title: "Food Service Worker", seniorTitle: "Food Service Supervisor" },
      { title: "Concierge", seniorTitle: "Head Concierge" },
    ],
  },

  // ──────────────────────────────────────────────────────────
  // Company name parts for realistic company names
  // ──────────────────────────────────────────────────────────
  companyParts: {
    prefixes: ["Alpha", "Beta", "Gamma", "Delta", "Apex", "Peak", "Summit", "Horizon", "Global", "National",
               "Prime", "First", "United", "Allied", "Pacific", "Atlantic", "Continental", "Universal", "General", "Standard",
               "American", "International", "Advanced", "Modern", "Digital", "Smart", "Dynamic", "Strategic", "Innovative", "Creative"],
    midwords: ["Tech", "Systems", "Solutions", "Consulting", "Services", "Industries", "Enterprises", "Group", "Partners", "Associates",
               "Analytics", "Design", "Management", "Development", "Research", "Marketing", "Capital", "Resources", "Networks", "Communications"],
    suffixes: ["Inc.", "LLC", "Ltd.", "Corp.", "Co.", "Group", "Holdings", "International", "Worldwide", "Technologies"],
  },

  // ──────────────────────────────────────────────────────────
  // Salary ranges by country (monthly in local currency)
  // ──────────────────────────────────────────────────────────
  salaryRanges: {
    US: { min: 3000, max: 12000, currency: "USD" },
    UK: { min: 2000, max: 9000, currency: "GBP" },
    CA: { min: 3000, max: 10000, currency: "CAD" },
    AU: { min: 4000, max: 12000, currency: "AUD" },
    IN: { min: 20000, max: 200000, currency: "INR" },
    DE: { min: 2500, max: 8000, currency: "EUR" },
    FR: { min: 2000, max: 7000, currency: "EUR" },
    JP: { min: 200000, max: 700000, currency: "JPY" },
    BR: { min: 3000, max: 20000, currency: "BRL" },
    MX: { min: 8000, max: 60000, currency: "MXN" },
    KR: { min: 2000000, max: 8000000, currency: "KRW" },
    NG: { min: 80000, max: 600000, currency: "NGN" },
    ZA: { min: 8000, max: 50000, currency: "ZAR" },
    PK: { min: 30000, max: 200000, currency: "PKR" },
    IT: { min: 1800, max: 6000, currency: "EUR" },
    ES: { min: 1700, max: 6000, currency: "EUR" },
  },

  // ──────────────────────────────────────────────────────────
  // Interests / hobbies
  // ──────────────────────────────────────────────────────────
  hobbies: [
    "Reading", "Hiking", "Photography", "Cooking", "Gardening", "Painting", "Drawing", "Cycling",
    "Swimming", "Running", "Yoga", "Meditation", "Gaming", "Blogging", "Traveling", "Music",
    "Playing guitar", "Playing piano", "Singing", "Dancing", "Woodworking", "Knitting", "Crocheting",
    "Baking", "Fitness", "Rock climbing", "Kayaking", "Bird watching", "Astronomy", "Chess",
    "Board games", "Martial arts", "Football", "Basketball", "Tennis", "Badminton", "Cricket",
    "Volunteering", "Coding", "Sketching", "Pottery", "Sculpting", "Film watching", "Theatre",
    "Creative writing", "Journaling", "Fishing", "Camping", "Home brewing", "Calligraphy", "Origami",
  ],

  kidHobbies: [
    "Drawing", "Playing video games", "Swimming", "Football", "Basketball", "Cycling",
    "Reading comics", "Playing with LEGO", "Dancing", "Singing", "Painting", "Board games",
    "Watching cartoons", "Playing with toys", "Coding games", "Skateboarding", "Gymnastics",
    "Playing with friends", "Baking cookies", "Storytelling", "Origami", "Pet care", "Puzzles",
  ],

  // ──────────────────────────────────────────────────────────
  // Favorites
  // ──────────────────────────────────────────────────────────
  favoriteColors: ["Blue", "Red", "Green", "Purple", "Black", "Orange", "Teal", "Navy", "Coral", "Lavender",
                   "Crimson", "Emerald", "Turquoise", "Indigo", "Magenta", "Amber", "Slate", "Sage", "Maroon", "Gold"],

  favoriteMovies: [
    "The Shawshank Redemption", "The Godfather", "Forrest Gump", "The Dark Knight", "Pulp Fiction",
    "Schindler's List", "The Lord of the Rings", "Inception", "Fight Club", "Goodfellas",
    "Interstellar", "The Matrix", "Spirited Away", "Parasite", "Life is Beautiful",
    "Good Will Hunting", "A Beautiful Mind", "Dead Poets Society", "The Lion King", "Toy Story",
    "Avatar", "Titanic", "Jurassic Park", "Star Wars", "Back to the Future",
    "The Silence of the Lambs", "No Country for Old Men", "Whiplash", "La La Land", "The Prestige",
  ],

  favoriteMusicGenres: [
    "Pop", "Rock", "Hip-hop", "Jazz", "Classical", "R&B", "Country", "Electronic", "Reggae",
    "Folk", "Soul", "Blues", "Metal", "Punk", "Indie", "Disco", "Gospel", "Latin", "K-pop", "Bollywood",
  ],

  favoriteSongs: [
    "Bohemian Rhapsody — Queen", "Imagine — John Lennon", "Smells Like Teen Spirit — Nirvana",
    "Hotel California — Eagles", "Stairway to Heaven — Led Zeppelin", "Like a Rolling Stone — Bob Dylan",
    "Yesterday — The Beatles", "What's Going On — Marvin Gaye", "Respect — Aretha Franklin",
    "Johnny B. Goode — Chuck Berry", "Purple Rain — Prince", "Born to Run — Bruce Springsteen",
    "Good Vibrations — The Beach Boys", "Johnny B. Goode — Chuck Berry", "A Day in the Life — The Beatles",
    "Hey Jude — The Beatles", "Superstition — Stevie Wonder", "Shape of You — Ed Sheeran",
    "Blinding Lights — The Weeknd", "Rolling in the Deep — Adele", "Someone Like You — Adele",
    "Uptown Funk — Bruno Mars", "Happy — Pharrell Williams", "Let It Go — Idina Menzel", "Despacito — Luis Fonsi",
  ],

  favoriteBooks: [
    "To Kill a Mockingbird — Harper Lee", "1984 — George Orwell", "The Great Gatsby — F. Scott Fitzgerald",
    "Harry Potter Series — J.K. Rowling", "The Lord of the Rings — J.R.R. Tolkien",
    "Pride and Prejudice — Jane Austen", "The Catcher in the Rye — J.D. Salinger",
    "Brave New World — Aldous Huxley", "The Alchemist — Paulo Coelho", "The Little Prince — Antoine de Saint-Exupéry",
    "Crime and Punishment — Fyodor Dostoevsky", "Don Quixote — Cervantes", "Anna Karenina — Leo Tolstoy",
    "The Hitchhiker's Guide to the Galaxy — Douglas Adams", "Sapiens — Yuval Noah Harari",
    "Thinking, Fast and Slow — Daniel Kahneman", "Atomic Habits — James Clear", "The Power of Now — Eckhart Tolle",
    "Rich Dad Poor Dad — Robert Kiyosaki", "How to Win Friends and Influence People — Dale Carnegie",
  ],

  // ──────────────────────────────────────────────────────────
  // Hair colors and blood types
  // ──────────────────────────────────────────────────────────
  hairColors: ["Black", "Dark Brown", "Brown", "Light Brown", "Blonde", "Dark Blonde", "Auburn", "Red", "Grey", "White"],
  bloodTypes: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
  bloodTypeWeights: [35, 6, 9, 2, 38, 7, 3, 1], // approximate global percentages * 100

  // ──────────────────────────────────────────────────────────
  // Civil status options
  // ──────────────────────────────────────────────────────────
  civilStatusAdult: ["Single", "Married", "Divorced", "Widowed", "In a relationship", "Separated"],
  civilStatusAdultWeights: [40, 40, 8, 4, 6, 2],

  // ──────────────────────────────────────────────────────────
  // School data
  // ──────────────────────────────────────────────────────────
  schoolTypes: ["Public", "Private", "Charter", "Magnet", "Religious"],
  schoolLevels: {
    primary: { label: "Primary School", gradeRange: [1, 6], ageRange: [6, 11] },
    middle: { label: "Middle School", gradeRange: [7, 8], ageRange: [12, 14] },
    high: { label: "High School", gradeRange: [9, 12], ageRange: [14, 18] },
    college: { label: "College / University", gradeRange: [1, 4], ageRange: [18, 22] },
    graduate: { label: "Graduate School", gradeRange: [1, 3], ageRange: [22, 30] },
  },

  // ──────────────────────────────────────────────────────────
  // Vehicle data
  // ──────────────────────────────────────────────────────────
  vehicles: [
    "Toyota Corolla", "Toyota Camry", "Honda Civic", "Honda Accord", "Ford F-150",
    "Chevrolet Silverado", "Hyundai Elantra", "Volkswagen Golf", "BMW 3 Series", "Mercedes C-Class",
    "Audi A4", "Mazda 3", "Nissan Altima", "Kia Sportage", "Subaru Forester",
    "Ford Explorer", "Jeep Grand Cherokee", "Toyota RAV4", "Honda CR-V", "Volkswagen Tiguan",
    "Tesla Model 3", "Tesla Model Y", "Chevrolet Bolt", "Toyota Prius", "Ford Mustang",
    "Dodge Challenger", "Hyundai Tucson", "Renault Clio", "Peugeot 308", "Fiat 500",
  ],

  // ──────────────────────────────────────────────────────────
  // Company size categories
  // ──────────────────────────────────────────────────────────
  companySizes: ["1–10", "11–50", "51–200", "201–1,000", "1,000+"],

  // ──────────────────────────────────────────────────────────
  // Email domains
  // ──────────────────────────────────────────────────────────
  emailDomains: ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "icloud.com",
                 "protonmail.com", "mail.com", "live.com", "aol.com", "zoho.com"],

  // ──────────────────────────────────────────────────────────
  // Online status
  // ──────────────────────────────────────────────────────────
  onlineStatuses: ["Active", "Away", "Offline"],

  // ──────────────────────────────────────────────────────────
  // Family composition templates
  // ──────────────────────────────────────────────────────────
  familyTemplates: [
    { members: 2, description: "Lives alone with one parent" },
    { members: 3, description: "Parents + 1 sibling" },
    { members: 4, description: "Parents + 2 siblings" },
    { members: 5, description: "Parents + 3 siblings" },
    { members: 2, description: "Married couple, no children" },
    { members: 4, description: "Married + 2 children" },
    { members: 3, description: "Single parent + 2 children" },
    { members: 6, description: "Large family with grandparents" },
    { members: 1, description: "Lives alone" },
    { members: 2, description: "Lives with a roommate" },
  ],
};
